### ISSUE TITLE
appId for using SAK/OPPGAVE

### ISSUE THREAD

**Issue by zeusbaba** [navikt/dokumentfordeling-integrations#27]
Integrasjon kreves alle apps er registrert slik at kan fåes `appId`  
Det må bestilles. se _placeholder_ fra kodebase `FagSystem`    
```
DOKFOR("FSxx", "DokFor");  
// see -> "confluence.../display/APPKAT/Applikasjons-ID" for detaljer   
```

**Comment by AStrand94** [comment]
Har sendt bestilling, venter på svar.

**Comment by AStrand94** [comment]
Audun bestiller. Lukker da vi har samme issue i navikt/dokumentfordeling
