### ISSUE TITLE
Validate consumers URLs i NAIS-miljø.  

### ISSUE THREAD

**Issue by zeusbaba** [navikt/dokumentfordeling-integrations#45]
URLs of Services we consume come from different Q-miljøer and this creates conflict when we use Fasit...  

For now, we need to hardkode URLs in `application-nais.properties` and validate i NAIS-miljø.  

Please cherry-pick the up2date URLs are from [k8s-nais-env.json](https://github.com/navikt/dokumentfordeling-integrations/blob/naiserator/k8s-nais-env.json) and use accordingly.

**Comment by AStrand94** [comment]
Husk: Vi holder issues i navikt/dokumentfordeling, selv om de referer til noe som skal gjøres i integrations.
